- webstyle/webstyle_templates_inspire.py
> Enabling tracking of noscript/ghostery

- websubmit/Bibtex.py
This improves the output from the author tool Bibtex.py for when no match is found or the citation key isn't recognized. Addresses user complaints. Tested against a random sample of arXiv hep-ph TeX source files and output reviewed by Heath.
In directory with TeX source files run
```python
import os
from invenio.websubmit_functions import Bibtex
texfiles = os.walk('.').next()[2]
with open('/tmp/testout.txt', 'w') as testout:
for texfile in texfiles:
with open(texfile) as tf:
refs = Bibtex.get_references(tf.read())
hlxu = Bibtex.process_references(refs, 'hlxu')
hlxe = Bibtex.process_references(refs, 'hlxe')
hx = Bibtex.process_references(refs, 'hx')
print >> testout, "processing %s renders:\nHLXU\n%s\n\nHLXE\n%s\n\nHX\n%s\n" \
% (texfile, hlxu, hlxe, hx,)
```
> WebSubmit: improve bibtex tool for authors

- webstyle/webstyle_templates_inspire.py
addresses issues with HTML validation introduced in  12aefc8
see
http://validator.w3.org/check?uri=http%3A%2F%2Finspirehep.net%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&ss=1&outline=1&verbose=1
> WebStyle: html validation fix for ghostery

- bibtasklets/bst_arxiv_doi_update.py
* Solves the issue where the script was generating "empty" bibupload
jobs.
* Cleans up PEP8 and PEP257 issues.
* Removes the indexing job generation and this should be sufficiently
taken care of by existing indexing jobs.
Reported-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> BibTasklets: arXiv DOI update fix

- bibtasklets/bst_fermilab_research_glance.py
- bibtasklets/bst_fermilab_research_glance_unit_test.py
* HOC's modularized FNAL report productivity analysis script
using lxml.html tree
* accompanying unit test.
following improvements by
Thorsten Schwander <thorsten.schwander@gmail.com>
** improved date arithmetic
** pep8 import order
** html cleanup
** copyright added
** improved tests
> Fermilab bibtasklet: FNAL report generator

- bibtasklets/bst_inspire_cds_synchro.py
* Adds the option to only generate record exports of records that
are missing the CFG_OTHER_SITE ID. E.g. already matched records
are filtered away.
> BibTasklets: CDS <-> INSPIRE record ID sync update

- bibedit/record_cdfnote.xml
* Just adds record_cdfnote.xml which is a BibEdit template
for CDF internal notes.
> bibedit: adds template for CDF internal notes

- feedboxes/portalbox-001-HEP-ne-100.html
- feedboxes/portalbox-002-HEP-rt-100.html
- feedboxes/portalbox-004-Jobs-rt-100.html
- feedboxes/portalbox-009-HepNames-rt-100.html
- webhelp/inspire_announce.html
- webhelp/search-tips.webdoc
- webstyle/websearch_templates_inspire.py
> general: update URL to search tips

- bibharvest/bibfilter_oaipos2inspire.py
* Fixes the imports from harvesting-kit in the PoS harvest filter.
> BibHarvest: fix PoS harvest

- bibtasklets/bst_arxiv_doi_update.py
> BibTasklets: no silent update from arXiv<->DOI matcher

- bibtasklets/bst_webcoll_postprocess.py
* Adds better error handling when posting newly recids to
INSPIRE Labs, allowing next run to catch up should anything go
wrong.
> BibTasklets: safer webcoll postprocess

- bibedit/record_article.xml
- bibedit/record_book.xml
- bibedit/record_book_chapter.xml
- bibedit/record_conference.xml
- bibedit/record_conference_paper.xml
- bibedit/record_hepnames.xml
- bibedit/record_preprint.xml
- bibedit/record_proceedings.xml
- bibedit/record_thesis.xml
* Improves a couple of record templates (xml files).
* Based on discussions on inspire-operations@SLAC.STANFORD.EDU.
* Has been tested on https://inspireheptest.cern.ch.
> bibedit: update record templates

- bibcheck/plugins/rename_subfield_filter.py
> bibcheck: new rule (rename subfield with filter)

- bibformat/format_elements/bfe_INSPIRE_bibtex.py
* special handling for collections that do not have cited references
* avoid IndexError in bookid lookup
* avoid printing empty abstract field
* fix typo in proceeedings
* pylint cleanup
> BibFormat: bibtex improvements

- bibtasklets/bst_scoap3_importer.py
* Fixes comparing PDFs/PDFAs against INSPIRE, thus no longer
creating a revision per day.
> BibTasklets: fix SCOAP3 handling of PDFA

- apsharvest/apsharvest_utils.py
> apsharvest: fix unzip function

- bibformat/format_elements/bfe_INSPIRE_authors.py
- bibformat/format_elements/bfe_INSPIRE_bibtex.py
* recognize more 2 letter initials in author names
* do not escape '_' in titles
> BibFormat: minor bibtex updates

- bibformat/format_templates/reference_update.bft
W3C validation fixes. There were 158 errors in the form, now 87. I cut my losses and stop here.
> BibFormat: ref-update form validation fixes

- bibcheck/plugins/rename_subfield_filter.py
> bibcheck: bug-fix rename_subfield_filter.py

- bibcheck/plugins/expand_subject.py
- bibcheck/rules.cfg
I don't have the environment to really test interplay with rules.cfg,
but I believe it works.
> bibcheck: new plugin - expand_subject

- bibcheck/plugins/correct_dates.py
> BibCheck: new correct_dates.py plugin

- bibformat/format_templates/Conf_HTML_detailed.bft
* display only 500__a, 500__o unused
> BibFormat: Conf detailed display fix

- bibtasklets/bst_fermilab.py
* adds experiments info for masters/bachelors
* adds collaboration info for masters/bachelors
* streamlined html generation
* flake8 and isort fixes
> BibTasklet: improving MASTERS/BACHELORS display

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Amends Friday night commit syntax error :-)
> OPS BibFormat: syntax error

- www/data_submission.py
Small fix to abstract the curator management
> Replace curators with an e-group list

- bibedit/volatile_check_ignore_HEP.xml
- bibedit/volatile_check_ignore_conference.xml
- bibedit/volatile_check_ignore_data.xml
- bibedit/volatile_check_ignore_experiment.xml
- bibedit/volatile_check_ignore_hepnames.xml
- bibedit/volatile_check_ignore_institution.xml
- bibedit/volatile_check_ignore_jobs.xml
- bibtasklets/bst_check4template.py
> New bibtasklet: bst_check4template

- bibcheck/plugins/fix_inspireid.py
> BibCheck: more inspire IDs

- bibtasklets/bst_prodsync.py
> bibtasklet: new bst_prodsync.py

- bibtasklets/bst_prodsync.py
* Fixes bug in call to format_record.
* Uses gzip to compress output when storing to filesystem.
* Store directly to AFS, rather than on limited NFS.
(closes #123)
> prodsync: better storage

- bibtasklets/bst_prodsync.py
> prodsync: add task_sleep_now_if_required

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Fixes handling of ISBNs in bfe_INSPIRE_enhanced_marcxml.
> BibFormat: bfe_INSPIRE_enhanced_marcxm. fix

- bibtasklets/bst_fermilab_research_glance.py
- bibtasklets/bst_fermilab_research_glance_unit_test.py
* 2 new FNAL divisions included:
Neutrino Divison and Long Baseline Neutrino Division.
* Accompanying unit test updated
> BibTaskLet: fermi research glance update

- bibformat/format_elements/bfe_INSPIRE_publi_info_latex.py
> BibFormat: introduced doi in LaTeX EU/US

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
- bibtasklets/bst_prodsync.py
* Improves bfe_INSPIRE_enhanced_marcxml by caching most of the
queries.
* Generates a tar file rather than a single .gz file
> prodsync: faster prodsync

- bibtasklets/bst_prodsync.py
* Makes prodsync on redis to cohexist with prodsync on AFS.
* Disables checking in of cited papers (not necessary).
* Improve verbosity.
> prodsync: improves redis sync

- bibformat/format_elements/bfe_INSPIRE_links.py
adds linking to ADS from bibcoded in 035__9/a
other fixes and streamlined code
prepares for switching of links for ads from 8564_u/y
> BibFormat: ADS linking improvement

- www/data_submission.py
* Fixes bug introduced with previous commit
1361b3332a0dd57eacc30be6c5a48c15366dec34.
> data: fix previous commit

- bibformat/format_elements/bfe_INSPIRE_abstract.py
- bibformat/format_templates/Default_HTML_detailed.bft
HTML fixes for the detailed record display
> BibFormat: html fixes for HD format

- bibtasklets/bst_dump_records.py
* Introduces sleeping points.
* Introduces progress time estimation.
* Try to improve speed by using format_record instead of print_record
> bibtasklet: bst_dump_records improvements

- bibformat/format_elements/bfe_INSPIRE_links.py
* metadata does not have ADS URLs in 8564 any longer
* ADS understands arXiv e-print identifiers for direct
record access, so use those when no bibcode is known
> BibFormat: improve links to ADS

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Exports in 701__z the ID of affiliation of supervisor.
* Exports in 773__0 the ID of corresponding Report (as defined by
$r).
* Fixes the export of the thesis instituion information.
* Exports in 961__c/x the creation_date and modification_date of the
corresponding record, as provided by the database (in the format
YYYY-MM-DD).
(see: inspirehep/inspire-next#721)
> BibFormat: new enhanced MARCXML fields

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
> BibFormat: match pubnotes in XME

- bibformat/format_templates/text_Latex_CV.bft
> BibFormat: improves escaping in LaTeX CV

- bibcheck/plugins/fix_inspireid.py
- bibcheck/rules.cfg
> BibCheck: more authors in fix_inspireid

- bibedit/record_journal.xml
* Adds a new template for journals.
> bedit: new journal template

- bibcheck/plugins/fix_spaces_in_journal.py
- bibcheck/rules.cfg
> BibCheck: new fix_spaces_in_journal

- bibtasklets/bst_prodsync.py
> bibtasklets: do not add broken records to sync

- bibformat/format_elements/bfe_INSPIRE_Hep_Erratum.py
ensure that pubnotes marked as errata in 773__m are displayed differently from the main pubnote
> BibFormat: improve erratum display in HD

- bibformat/format_elements/bfe_INSPIRE_publi_info.py
- bibformat/format_templates/Default_HTML_citation_log.bft
- bibformat/format_templates/Default_HTML_similarity.bft
- bibformat/format_templates/reference_update.bft
* erratum/addendum display in pubnotes
* add line-break to improve citations tab display
* fix pubnote display in ref correction form
* add volume prefix "no." to pubnotes
> BibFormat: various format improvements

- bibformat/format_templates/Default_HTML_similarity.bft
> BibFormat: remove line break added in d94adc5

- bibtasklets/bst_inspire_cds_synchro.py
* Exports from CDS the IDS of all CDS records that are CERN.
* Uses previous step extracted information on INSPIRE to correctly
decide if a record is CERN relevant or not.
* Rather than simply appending new IDs, send bibupload correct
with amended IDs, so that, on INSPIRE side, IDs can be moved
between 595 and 035 if necessary.
> BibTasklet: bst_inspire_cds_synchro improvements

- bibcheck/plugins/delete_subfield_filter.py
- bibcheck/rules.cfg
* deletes subfield given as argument
* filter on subfield optional
> bibcheck: new plugin - delete_subfield_filter.py

- webhelp/easy-search.webdoc
* journal names may contain spaces, properly
enclose search term in double-quotes
> WebSearch: quote journal names

- bibcheck/rules.cfg
there's a problem with the previous merge of KS pull request 
> BibCheck: fix KS rule

- bibcheck/plugins/sort_family_names.py
- bibcheck/rules-others.cfg
- bibcheck/rules.cfg
> BibCheck: new sort_family_names plugin

- bibharvest/bibfilter_oaiarXiv2inspire.py
> bibfilter: fix author check

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Introduces links between PhdAdvisors and HepNames.
(closes #184)
* Introduces links between Experiments and Institutions.
(closes #185)
* Autoclaim HepNames based on INSPIRE-Ids.
> BibFormat: INSPIRE_enhanced_marcxml improvements

- bibtasklets/bst_refresh_author_profiles.py
> BibTaskLets: add bst_refresh_author_profiles

- bibconvert/arxiv-to-inspire-categories.kb
* Introduces new physics.data-an -> Data Analysis and Statistics
> bibconvert: new physics.data-an mapping

- bibformat/format_templates/Exp_HTML_brief.bft
fixes a bad comment in format template
> BibFormat: fix html comment error

- bibformat/format_templates/Exp_HTML_brief.bft
> BibFormat: fix typo in previous commit

- bibformat/format_templates/Conf_HTML_brief.bft
- bibformat/format_templates/Journal_Inspire_HTML_brief.bft
> BibFormat: fix html errors in templates

- bibformat/format_elements/bfe_INSPIRE_inproc_booktitle.py
> BibFormat: fix typo affecting subtitles

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Also fix bug in exporting obsolete ICNs.
(closes #206)
> BibFormat: export bibdocfiles in FFT

- bibrank/citation.cfg
This complements https://github.com/inspirehep/invenio/pull/329/files
> BibRank: adds erratum subfield definition

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
> BibFormat: typo 110__w->110__x

- bibcheck/plugins/fix_double_longitude.py
- conf/invenio-local.conf-example
Signed-off-by: Jacopo Notarstefano <jacopo.notarstefano@cern.ch>
Co-authored-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> BibCheck: fix double longitude (closes #210)

- bibtasklets/bst_consyn_harvest.py
* avoid repeated searching in AFS directory
* minor bug fixes and cosmetic improvements
> BibTaskLet: speed up consyn harvest

- bibedit/record_institution.xml
> BibEdit: latitude template fix

- bibformat/format_elements/bfe_INSPIRE_links.py
> BibFormat: introduce INIS link

- bibformat/format_elements/bfe_INSPIRE_Hep_Bookinfo.py
- bibformat/format_elements/bfe_INSPIRE_Hepnames_Institution_PHD.py
- bibformat/format_elements/bfe_INSPIRE_Hepnames_Institution_UG.py
- bibformat/format_elements/bfe_INSPIRE_jobs_contact.py
> BibFormat: remove duplicate url params

- bibformat/format_elements/bfe_INSPIRE_links.py
* Updates KEK scan URL algorithm to reflect the recent change.
(See https://rt.inspirehep.net/Ticket/Display.html?id=607395)
* Amends INIS algorithm to not do useless replaces.
Co-Authored-By: Thorsten Schwander <thorsten.schwander@gmail.com>
> BibFormat: fixes to kek linking

- bibcheck/plugins/fix_double_longitude.py
- bibcheck/plugins/geocode_all_the_things.py
As for #210, I haven't run or tested this code, but it looks right, so it must also be correct : )
* First commit fixes my twitchy eye when I look at that previous commit.
* Second commit geocodes all Conferences and Institutions that could have it. It's possible that we run into the API limits on this one; it should be enough to restart the task the next day (it looks idempotent).
> BibCheck: geocode all the things

- bibcheck/plugins/geocode_all_the_things.py
* record geocode version in 034__2
* record match quality/type in 034__q
* minor bugfix
* city, zip, country before full lookup
> BibCheck: improve geocoding

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
> BibFormat: xme to properly match institutions

- www/bais.py
> www: new /bais.py/unlinked

- bibtasklets/bst_dump_records.py
- bibtasklets/bst_prodsync.py
> prodsync: run R/O on slave DB

- bibcheck/plugins/kekmove.py
> bibcheck: really normalized KEK IDs

- bibcheck/plugins/kekmove.py
> bibcheck: more KEK ID normalization

- bibformat/format_elements/bfe_INSPIRE_current_institution.py
- bibformat/format_templates/Hepnames_HTML_brief.bft
- bibformat/format_templates/Hepnames_HTML_detailed.bft
> BibFormat: current institution in HepNames

- bibformat/format_elements/bfe_INSPIRE_hdl.py
> BibFormat: fix bfe_INSPIRE_hdl

- bibcheck/plugins/type_code.py
* add missing type codes to 980__a based on metadata
> BibCheck: typecode plugin

- bibcheck/rules.cfg
> BibCheck: typecode rule added

- feedboxes/portalbox-017-Experiments-rt-100.html
* link to Experiments list
* urlescape links
> FeedBoxes: update Experiments feedbox

- webstyle/webstyle_templates_inspire.py
* XHTML-1.0-Transitional requires type attr for style
> WebStyle: fix for html validation

- bibcheck/plugins/refcheck.py
* check consistency of info in 999C5
- specifically
check that cited_recid in 999C50 matches with
journal citation and/or report number search
* issue warnings for various reference problems
> BibCheck: new plugin refcheck

- bibcheck/plugins/superseeded_refs.py
* if recid in 999C50 is superseeded replace with
superseeding recid
> BibCheck: plugin updating 999C50

- bibcheck/plugins/refcheck.py
> BibCheck: refcheck plugin compatible with python 2.6

- bibcheck/plugins/refcheck.py
> BibCheck: track curator in refcheck plugin

- bibcheck/plugins/refcheck.py
> BibCheck: strip 'doi:' prefix

- bibformat/format_elements/bfe_INSPIRE_authors.py
* Group, Team, etc. without appended Collaboration
> BibFormat: improve collaboration display

- bibformat/format_templates/text_Latex_CV.bft
* inspire part of inspirehep/invenio#377
* closes #213
> BibFormat: cvlatex improvements

- bibformat/format_templates/text_Latex_CV.bft
> BibFormat: CV LaTeX whitespace fix

- kbs/pdg.kb
> kbs: update PDG

- feedboxes/portalbox-009-HepNames-rt-100.html
> Feedboxes: update HEPNames feedbox

- bibcheck/plugins/rename_field_filter.py
> bibcheck: new rename_field_filter plugin

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
> BibFormat: deleted record support in XME

- webhelp/easy-search.webdoc
- webstyle/websearch_templates_inspire.py
Annette asked to add `Chin.Phys.C` to EasySearch pull-down options for journal. This should do it.
> EasySearch: add journal option Chin.Phys.C

- webhelp/easy-search.webdoc
- webstyle/websearch_templates_inspire.py
> EasySearch: remove volume letter from Chin.Phys.

- bibformat/format_elements/bfe_INSPIRE_Hepnames_update_button.py
- feedboxes/portalbox-009-HepNames-rt-100.html
> Preparing for newlabs switch

- bibtasklets/bst_hal.py
ensure that connections don't hang forever, http://docs.python-requests.org/en/master/user/quickstart/#timeouts
> BibTaskLet: HAL add request timeout

- bibtasklets/bst_align_hepnames_and_bais.py
> bibtasklets: new bst_align_hepnames_and_bais

- bibtasklets/bst_hepdata.py
> bibtasklets: new hepdata harvester

- bibtasklets/bst_hepdata.py
> bst_hepdata: improve titles

- bibtasklets/bst_prodsync.py
* In Redis sync, if the queue has not yet been emptied by Labs,
skip pushing updates to the next run.
> bst_prodsync: skip if queue is not empty

- bibtasklets/bst_autoclaim.py
> bibtasklet: new ORCID autoclaim functionality

- www/doi2orcid.py
> doi2orcid: new util to export ORCIDs for DOIs

- bibtasklets/bst_arxiv_doi_update.py
fixes https://github.com/inspirehep/inspire/issues/297
> BibTaskLet: handle multiple DOIs per record

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
> BibFormat: naked affiliations in XME

- kbs/pdg.kb
* Adds new PDG particles based on
http://pdg.lbl.gov/2017/pdgid/PDGIdentifiers-2017v0.txt
> kbs: new PDG particles

- bibedit/record_accelerator.xml
- bibedit/volatile_check_accelerator.xml_ignore
* Updates experiment templates and creates accelerator templates,
in order to add accelerators to the collection.
> bibedit: update templates

- miscutil/Makefile
- miscutil/bin/Makefile
- miscutil/bin/retryupload
> miscutil: new retryupload script

- bibcheck/plugins/bibdocurlspaces.py
> BibCheck: plugin urlescape path component in 8564_u

- bibtasklets/bst_hepdata.py
* ignore position in hepdata record comparison
> BibTaskLet: hepdata update fix

- webstyle/robots.txt
> robots.txt: disable /youraccount/

- apsharvest/apsharvest_config.py
- apsharvest/apsharvest_engine.py
- bibtasklets/bst_apsharvest.py
Co-authored-by: Micha Moskovic <michamos@gmail.com>
> apsharvest: adapt to new v2 API

- bibharvest/bibfilter_oaipos2inspire.py
Co-Authored-By: Florian Schwennsen <florian.schwennsen@desy.de>
> BibHarvest: updated URLs for PoS

- bibformat/format_elements/bfe_INSPIRE_datasets_link.py
> BibFormat: HepData link for datasets updated

- bibformat/output_formats/HB.bfo
- bibformat/output_formats/HD.bfo
> BibFormat: JournalsNew format defs

- feedboxes/portalbox-002-HEP-rt-100.html
- feedboxes/portalbox-004-Jobs-rt-100.html
- feedboxes/portalbox-009-HepNames-rt-100.html
- feedboxes/portalbox-014-Conferences-rt-100.html
- feedboxes/portalbox-015-Institutions-rt-100.html
- feedboxes/portalbox-017-Experiments-rt-100.html
- feedboxes/portalbox-019-Journals-rt-100.html
> PortalBox: add content-policy

- feedboxes/portalbox-003-Jobs-ne-100.html
- feedboxes/portalbox-004-Jobs-rt-100.html
- feedboxes/portalbox-009-HepNames-rt-100.html
- feedboxes/portalbox-015-Institutions-rt-100.html
> PortalBox: validation fixes

- bibtasklets/bst_hepdata.py
* Adds HEP records with the corresponding HEPData ID.
> hepdata: enrich HEP records

- bibformat/format_elements/bfe_INSPIRE_datasets_link.py
see
https://rt.inspirehep.net/Ticket/Display.html?id=754240
this needs rebuild of the brief format cache via `bibreformat` 
> BibFormat: fix check if data parent

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Do not add a 773__0 if there is already one.
(closes #330)
* Enhances fields about relations (510, 530, 78x).
> bibformat: improvements to XME

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Fixes bug in enhanching 77x fields.
(closes #332)
> BibFormat: XME fix 77x export

- bibtasklets/bst_prodsync.py
* Adds more options to get ready for switching to R/O mode.
> bst_prodsync: add more options

- bibtasklets/bst_claimsync.py
> bibtasklets: new bst_claimsync

- bibtasklets/bst_claimsync.py
* Fixes exporting of claims only when flag is actually set to
-2 or 2.
* Re-export any claim associated with a profile that got modified
within the last 2 days (just to be sure that everything is already
in sync).
> bst_claimsync: fix flag export

- bibcheck/rules.cfg
> BibCheck: strip trailing dot from ORCIDs

- bibtasklets/bst_inspire_cds_synchro.py
> cds-synchro: export 595 correctly

- bibformat/format_elements/bfe_INSPIRE_Hepnames_update_button.py
companion to https://github.com/inspirehep/invenio/pull/434
> BibFormat: use CFG_LABS_HOSTNAME

- bibcheck/plugins/fix_inspireid.py
Added 9 items to list that need corrected INSPIRE-IDs
> Bibcheck: Update fix_inspireid.py

- bibtasklets/bst_prodsync.py
* Previously, modified records to sync were searched on the master DB,
but the XME generation was reading from the slave DB, leading to stale
information in case the slave had not been updated yet. This is fixed by
performing all searches on the slave. This can result in outdated
records being sent in the prodsync, but those will eventually be updated
in the next run of the prodsync.
> prodsync: don't produce XME from stale data

- webstyle/robots.txt
> WebStyle: adjust robots.txt

- bibformat/format_elements/bfe_INSPIRE_links.py
- kbs/weblinks.kb
OSTI requested change to be in line with their branding
> BibFormat: adjust text for OSTI links

- bibcheck/plugins/fix_inspireid.py
> BibCheck: fix whitespace in code

- bibtasklets/bst_orcidsync.py
Count the number of ORCID tokens (and relative data) to be synch'ed (and thus sent to Redis). This is used at Lab's side to check weather the right number of token has been processed.
> orcidsync: count tokens to be synch'ed

- bibharvest/bibfilter_oaicds2inspire.py
* ensures CDS id search only matches CDS ids
> BibHarvest: improve CDS bibfilter id search

- bibconvert/demo-records.xml
- bibconvert/test_record_spires.xml
- bibformat/format_elements/bfe_INSPIRE_Conferences_PROC.py
- bibformat/format_elements/bfe_INSPIRE_doi.py
- bibformat/format_elements/bfe_INSPIRE_journal_links.py
- bibformat/format_elements/bfe_INSPIRE_latex_doi.py
- bibformat/format_elements/bfe_referenceinp.py
- bibformat/format_elements/bfe_references.py
Same as https://github.com/inspirehep/inspirehep-search-js/pull/66 ;-)
> Link DOIs to preferred resolver

- webstyle/websearch_templates_inspire.py
* when there are no collection specific examples return empty string
> WebSearch: fix search examples template

- bibtasklets/bst_fermilab.py
- bibtasklets/bst_fermilab_research_glance.py
> BibTaskLet: use Fermilab collection

- bibcheck/plugins/fix_inspireid.py
> BibCheck: Update plugin fix_inspireid.py

- bibformat/format_templates/Hepnames_HTML_detailed.bft
> BibFormat: cleanup of link in HepNames detailed

- bibformat/format_elements/bfe_INSPIRE_Hep_Erratum.py
- bibformat/format_elements/bfe_INSPIRE_conference.py
> BibFormat: special case #DONE: in 773__x

- bibcheck/plugins/isbn_normalize.py
* avoids errors from stray [xX] chars
> BibCheck: improved isbn_normalize

- bibformat/format_elements/bfe_references.py
> BibFormat: pylint cleanup

- feedboxes/inspire_update_feedboxes.py
* adapts to use python twitter version 3.x
* uses application only authentication (read-only)
> FeedBoxes: update for python-twitter 3.x

- bibformat/format_elements/bfe_INSPIRE_Hepnames_Arxiv.py
- bibformat/format_templates/Hepnames_HTML_detailed.bft
https://blogs.cornell.edu/arxiv/2018/05/04/release-search-v0-2-some-notes-on-names/
> BibFormat: new arXiv (author-)search URLs

- bibformat/format_elements/bfe_INSPIRE_publi_info.py
> BibFormat: remove string #DONE:

- bibcheck/plugins/fix_inspireid.py
- bibcheck/rules.cfg
-added replace_LokajicekM_inspireid to rules.cfg
-added 9 entries to CHANGES list in fix_inspireid plugin
> BibCheck: update rules.cfg and plugin fix_inspireid 

- bibcheck/plugins/fix_inspireid.py
- bibcheck/plugins/type_code.py
-Added one author update to CHANGES in fix_inspireid.py
-Added three journals to JOURNAL_PUBLISHED_DICT in type_code.py
> BibCheck: update fix_inspireid and type_code plugins

- bibedit/volatile_check_HEP.xml_ignore
- bibedit/volatile_check_data.xml_ignore
> BibTaskLet: don't skip ORCID in volatile check

- bibtasklets/bst_fermilab_research_glance.py
- bibtasklets/bst_fermilab_research_glance_unit_test.py
-added SLIDES and POSTER to pubtypes
-reordered glossary and added SLIDES and POSTER
-added SLIDES and POSTER to bst_fermilab_research_glance_unit_test.py
> BibTasklets: updated bst_fermilab_research_glance

- bibformat/format_elements/bfe_INSPIRE_links.py
update URL for mathscinet links
> BibFormat: update MSNET link

- bibtasklets/bst_scoap3_importer.py
> BibTaskLet: fix indentation error

- bibtasklets/bst_scoap3_importer.py
> BibTaskLet: clarify loop variable name

- bibtasklets/bst_fermilab_research_glance.py
-updated links in output to point to Fermilab collection
> BibTasklets: Update bst_fermilab_research_glance.py

- bibtasklets/bst_fermilab.py
-added 'slides' and 'poster' to report number series
> BibTasklets: update bst_fermilab.py

- bibcheck/plugins/remove_duplicate_repno.py
> BibCheck: add plugin to dedupe report numbers

- feedboxes/portalbox-002-HEP-rt-100.html
> PortalBox: update labs link

- bibcheck/plugins/fix_inspireid.py
-added line to change INSPIRE-00250377 to INSPIRE-00493721
in HEP for Jiri Kral of Jyvaskyla U.
> BibCheck: added line for Jyvaskyla U. to fix_inspireid

- bibcheck/plugins/fix_inspireid.py
> BibCheck: fix bad whitespace in previous merge

- feedboxes/portalbox-015-Institutions-rt-100.html
* update link to institutions list
* update email address for institutions feedback
> PortalBoxes: update Institutions box

- bibformat/format_elements/bfe_GRID_ID.py
- bibformat/format_templates/Inst_HTML_detailed.bft
> BibFormat: display GRID ID in Inst

- bibformat/format_templates/Inst_HTML_detailed.bft
> BibFormat: inst HD html validation fixes

- bibformat/format_templates/Inst_HTML_detailed.bft
> BibFormat: more inst html fixes

- bibformat/format_templates/Inst_HTML_detailed.bft
> BibFormat: final inst html fix

- bibformat/format_templates/Exp_HTML_brief.bft
- bibformat/format_templates/Exp_HTML_detailed.bft
> BibFormat: quote exp acronym search

- bibedit/record_institution.xml
* Corrects 510__a to use old instead of new ICN.
* Adds GRID field.
> bibedit: update INST template

- bibformat/format_elements/bfe_INSPIRE_exp_link.py
> BibFormat: quote experiment name in search link

- bibformat/format_elements/bfe_INSPIRE_Hepnames_update_button.py
> BibFormat: change HN updates link

- feedboxes/portalbox-009-HepNames-rt-100.html
> PortalBox: correct HN additions link

- bibformat/format_elements/bfe_INSPIRE_exp_link.py
> BibFormat: allow for repeated subfield in exp link

- webhelp/easy-search.webdoc
> WebHelp: fixes journal names in easy search

- bibcheck/plugins/fix_inspireid.py
> BibCheck: revert author numbering

- bibcheck/plugins/journal_names.py
* update of plugin journal_names
* proper treatment of dots
* all variants normalized
* short names (711) in variants (730)
* variants are not repeated
* codens and variants not in other record
* option to sort variants
> WIP: bibcheck: new plugin - journal_names_var

- bibcheck/plugins/journal_names.py
* update of plugin journal_names
* proper treatment of dots
* all variants normalized
* short names (711) in variants (730)
* variants are not repeated
* codens and variants not in other record
* option to sort variants
> bibcheck: updated plugin - journal_names

- bibcheck/plugins/type_code.py
- Added JCAP to dictionary of journals that get Published tag
> BibCheck: Added journal to type_code plugin

- webhelp/additions.webdoc
- webstyle/docextract_templates_inspire.py
> WebHelp: update additions link

- bibtasklets/bst_fermilab.py
- bibtasklets/bst_fermilab_research_glance.py
- bibtasklets/bst_fermilab_research_glance_unit_test.py
- included CODE report numbers in bst_fermilab.py, bst_fermilab_research_glance.py, and bst_fermilab_research_glance_unit_test.py
> BibTasklets: Add CODE to Fermilab tasklets

- bibformat/format_elements/bfe_INSPIRE_links.py
> BibFormat: update links to ADS

- feedboxes/portalbox-002-HEP-rt-100.html
> PortalBox: update ADS link

- bibformat/format_elements/bfe_INSPIRE_bibtex.py
> BibFormat: make bibtex recognize bachelor thesis

- bibformat/format_elements/bfe_INSPIRE_bibtex.py
* populate school field for thesis entries from 502__c
and use 100__u as a fallback 
> BibFormat: use 502__c in bibtex for thesis

- bibcheck/notimechange-rules.cfg
* delete 500__a:* Brief entry * for HEP CORE records
> bibcheck: new rule: delete Brief entry for CORE

- webstyle/webstyle_templates_inspire.py
* temporary banner announcing mailing list
> WebStyle: add usability testing banner

- webstyle/webstyle_templates_inspire.py
* we have sufficient number of subscribers and remove the temporary banner
This reverts commit 7835dfe6d174c251c02adaa1ad204a372b87f2a2.
> Revert "WebStyle: add usability testing banner"

- bibtasklets/bst_scoap3_importer.py
* adapt to new scoap3 repo api
* use incremental OAI-PMH harvest to find updates
> BibTaskLets: update scoap3 tasklet

- bibformat/format_templates/reference_update.bft
> BibFormat: add recid to subject line in hrf

- bibformat/format_templates/reference_update.bft
- www/reference_update.py
* use direct python rt api for ticket submission 
instead of submission via slac form_mail.pl email gateway
* improve presentation of reference changes
> BibFormat: improve handling of HRF

- www/reference_update.py
> BibFormat: improve message on ref change request

- bibformat/format_elements/bfe_INSPIRE_links.py
> BibFormat: urlencode arXiv id

- bibtasklets/bst_scoap3_importer.py
> BibTaskLet: fix scoap3 last_update

- bibtasklets/bst_scoap3_importer.py
> BibTaskLet: SCOAP3 fix arXiv id search

- bibexport/sitemap.cfg
- webhelp/join.webdoc
- webstyle/inspireproject_webinterface.py
- webstyle/inspireproject_webinterface_templates.py
- webstyle/invenio_inspire.css
- webstyle/webstyle_templates_inspire.py
* add a tooltip for Jobs redirect
* exclude legacy Jobs from sitemap
* update help for subscription to jobs mailing list
> WebStyle: tooltip for Jobs redirect to labs

- bibformat/format_elements/bfe_ROR_ID.py
- bibformat/format_templates/Inst_HTML_detailed.bft
> BibFormat: add ROR id format element

- bibformat/format_templates/Hepnames_HTML_detailed.bft
- webstyle/Makefile
- webstyle/betalink.css
- webstyle/websearch_templates_inspire.py
- webstyle/webstyle_templates_inspire.py
* add a button/link on HepNames detailed display to open a new tab showing the associated author info on labs
* add a button to the HEP search box to open a new tab executing the same search query on labs
> WebStyle: add links to beta

- webstyle/websearch_templates_inspire.py
> WebStyle: fix quotes for attribute

- webstyle/robots.txt
> WebStyle: robots.txt update

- www/reference_update.py
> RefUpdate: handle empty form requests gracefully

- webstyle/invenio_inspire.css
- webstyle/webstyle_templates_inspire.py
> WebStyle: remove unused hepdata css/js

- bibtasklets/bst_dump_records.py
> BibTaskLet: add viewport to index of dumps

- bibtasklets/bst_arxiv_doi_update.py
> BibTaskLet: fix asana subtask creation

- bibtasklets/bst_prodsync.py
> BibTaskLet: prodsync handle deleted citations

- bibtasklets/bst_prodsync.py
> BibTaskLet: fix typo in previous commit

- webstyle/webstyle_templates_inspire.py
> WebStyle: make INSPIRE logo scalable

- bibformat/format_elements/bfe_INSPIRE_bibtex.py
> BibFormat: handle multiple 773 in bibtex note field

- webstyle/inspireproject_webinterface.py
> WebStyle: update Error handling in jobs matrix

- www/data_submission.py
handle empty requests to the data_submission URL gracefully
> data: handle no arguments given

- bibtasklets/bst_prodsync.py
> bibtasklets: allow end marker in redis prodsync

- bibcheck/plugins/fix_ref_jhep_volume.py
* improved preformance
* add dealing with PTEP and MDPI Physics
* TBD: filter of the bibcheck-rule
> bibcheck: updated rule: fix_ref_jhep_volume

- bibcheck/weekly-rules.cfg
> bibcheck: updated rule for KAOS_fix_ref.JCAP_JHEP

- webstyle/docextract_templates_inspire.py
- webstyle/inspireproject_webinterface.py
> WebStyle: parametrize labs hostname

- bibformat/format_templates/RSS.xsl
- bibtasklets/bst_align_hepnames_and_bais.py
- webhelp/search-tips-index-list.webdoc
- webhelp/search-tips.webdoc
- webstyle/inspireproject_webinterface_templates.py
* change hardcoded URLs in various help pages and elsewhere
to old.inspirehep.net
> Web: update URL

- bibformat/format_elements/bfe_INSPIRE_bibtex.py
- bibtasklets/bst_fermilab_research_glance.py
- www/doi2orcid.py
> Web: continue parametrize site url

- bibformat/format_elements/bfe_INSPIRE_links.py
> BibFormat: substitute site name in links

- bibformat/format_elements/bfe_INSPIRE_journal_links.py
> BibFormat: deal with hardcoded URL

- bibformat/format_templates/Hepnames_HTML_detailed.bft
- webstyle/websearch_templates_inspire.py
> WebStyle: update beta link

- bibformat/format_templates/Hepnames_HTML_detailed.bft
> BibFormat: change wording in beta link

- bibtasklets/bst_hepdata.py
> BibTaskLet: add retry to hepdata dumper

- bibtasklets/bst_arxiv_doi_update.py
> BibTaskLet: better journal normalization

- bibformat/format_elements/bfe_INSPIRE_links.py
> BibFormat: link PDF with doctype CDS

- webstyle/inspireproject_webinterface.py
- webstyle/inspireproject_webinterface_templates.py
> WebStyle: improve error handling

- bibtasklets/bst_fermilab.py
- bibtasklets/bst_fermilab_research_glance.py
-Added 'CRADA' to report numbers in bst_fermilab and bst_fermilab_research_glance
-Improved error handling in bst_fermilab
> BibTasklets: Update Fermilab tasklets

- bibtasklets/bst_hal.py
Change HAL identifier harvest to use a cursor into search results instead of pagination by offset.
This should be more efficient on the remote end.
Also lower the pagination size from 10k to 5k
> BibTaskLet: improve hal identifier harvest

- webstyle/robots.txt
> WebStyle: update robots.txt

- bibtasklets/bst_scoap3_importer.py
> BibTaskLets: add retry to scoap3 harvest

- bibtasklets/bst_dump_records.py
> BibTaskLets: drop Jobs coll from monthly dumps

- bibcheck/rules.cfg
> BibCheck: fix regexp in fermi rule

- bibformat/format_elements/bfe_INSPIRE_links.py
> BibFormat: correct zblatt link

- bibtasklets/bst_hepdata.py
> BibTaskLets: reduce chunk size for HepData retrieval

- webstyle/webstyle_templates_inspire.py
> WebStyle: update switchoff banner
