- bibtasklets/bst_webcoll_postprocess.py
* Fixes an issue where the webcoll post-process task could cause
the webcoll task to be stopped in the BibSched with errors.
Reported-by: Samuele Kaplun <samuele.kaplun@cern.ch>
Reported-by: Thorsten Schwander <thorsten.schwander@gmail.com>
> BibTasklets: webcoll post process error free

- bibconvert/cds2inspire.xsl
- bibharvest/bibfilter_oaicds2inspire.py
* Updates the CDS to INSPIRE stylesheet to properly map experiments
in 693.
* Now adds 980__a:NOTE for CMS-PAS records.
* No longer adds 690__c:THESIS etc.
> BibHarvest: CDS import fixes

- bibformat/format_elements/bfe_INSPIRE_Hepnames_ADS_link.py
- bibformat/format_elements/bfe_INSPIRE_Hepnames_Native_Name.py
- bibformat/format_elements/bfe_INSPIRE_Hepnames_ORCID.py
- bibformat/format_templates/Hepnames_HTML_detailed.bft
Alberto/ADS points out that the links to ADS author page from the HepNames Detailed page are incorrect
This patch introduces a new format_element bfe_INSPIRE_Hepnames_ADS_link.py which generates the correct link to include in the format template instead of inserting field 100__q verbatim.
Also included a simple fix to the ORCID link which is missing quotes around the href value.
> BibFormat Hepnames Detailed HTML updates

- bibformat/format_elements/bfe_INSPIRE_Hepnames_ADS_link.py
- bibformat/format_templates/Hepnames_HTML_detailed.bft
use bibformat built-in escaping in the template instead of manual escaping in the element following Sam's recommendation on previously deployed code.
> BibFormat: fix escape HepNames ADS link

- bibtasklets/bst_inspire_cds_synchro.py
* Keep basing synchronization on the 035 field.
> BibTasklets: better default in cds-synchro

- websubmit/CONFSUBMITcreate.tpl
- websubmit/CONFSUBMITmodify.tpl
* Adds $$2INSPIRE in 65017 fields of conferences.
> WebSubmit: $$2INSPIRE 65017

- bibformat/format_elements/bfe_INSPIRE_Hepnames_update_button.py
- feedboxes/portalbox-009-HepNames-rt-100.html
* Updates HepNames update link to point to new forms in
labs.inspirehep.net.
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
> bibformat: hepnames update link update

- bibformat/format_elements/bfe_INSPIRE_Conference_cite_date.py
- bibformat/format_elements/bfe_INSPIRE_Conferences_date.py
- bibformat/format_elements/bfe_INSPIRE_authors.py
- bibformat/format_elements/bfe_INSPIRE_bibtex.py
- bibformat/format_elements/bfe_INSPIRE_inproc_booktitle.py
- bibformat/format_elements/bfe_texkey.py
- bibformat/format_templates/INSPIRE_BibTeX.bft
- bibformat/format_templates/INSPIRE_BibTeX_abstract.bft
- bibformat/output_formats/HXA.bfo
Multiple improvements, among them:
* spaces between author initials
* spaces in journal names
* correct @entry type:
@article, @inproceedings, @inbook, @book, @phdthesis etc.
* multiple pubnotes delegated to note field
* bibtex date regex fix
* multiple bug fixes
* increased author limit to 10
* removed trailing comma
* corrected SLACCITATION
* correct placement of Jr, IV etc.
* Russian Yu within {\relax }
* improved @inproceedings
* collaboration field omits word collaboration
* JHEP vol. number problem fixed
* flake8 compliance
* initial ISBN support
* url support, filtered by extension
* escape special TeX chars in title
* booktitle support
* introduces a format element for bibliographic information
on "booktitle" of parent record to be used in BibTeX format
of ConferencePapers
* …
> BibFormat: multiple bibtex improvements

- bibformat/format_templates/reference_update.bft
- bibtasklets/bst_consyn_harvest.py
simple fix for logging, which currently looks like
....  URL could not be opened: %shttps://.........
e.g.
2015-06-23 00:12:18 --> Downloading https://consyn.elsevier.com/batch/download?key=MTM2OTMtMDAwMDEtRlVMTC1YTUwuWklQOzEzNjkzO0FIb2x0a2FtcDs%3d to /afs/cern.ch/project/inspire/uploads/elsevier/consyn/13693-00001-FULL-XML.ZIP
2015-06-23 00:20:39 --> URL could not be opened: %shttps://consyn.elsevier.com/batch/download?key=MTM2OTMtMDAwMDEtRlVMTC1YTUwuWklQOzEzNjkzO0FIb2x0a2FtcDs%3d
2015-06-23 00:20:39 --> URL could not be opened: 
2015-06-23 00:20:39 --> Traceback (most recent call last):
File "/opt/cds-invenio/lib/python/invenio/bibsched_tasklets/bst_consyn_harvest.py", line 346, in download_feed
download_url(fileUrl, "zip", outFilename, 5, 60.0)
File …
> BibTaskLets: fix typo in consyn harvest logging

- bibtasklets/bst_cnumcatchup.py
this tasklet checks for updated conference records and updated proceedings records and ensures the info is updated in the cached brief format of associated HEP records
> BibTaskLet: cnum catchup for HB format

- bibformat/format_templates/Conf_HTML_detailed.bft
Kirsten is moving 500__o to 500__a for Conference collection. This patch adjusts detailed display template to display both fields. Once the metadata update is complete, 500__o should be removed from the template.
> BibFormat: transitional conf detailed display fix

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
- bibformat/format_templates/INSPIRE_Enhanced_MARCXML.bft
- bibformat/format_templates/OAI_MARC_ENHANCED.bft
- bibformat/output_formats/XME.bfo
- bibformat/output_formats/XOAIMARCE.bfo
- conf/invenio-local.conf-example
* Introduces new XME format with enhanced MARCXML sporting:
100/700 $x with Record ID of linked HepName,
$y with True/False if the signature is claimed
$z with Record ID of institution
371/110 $z with Record ID of institution
502     $z with Record ID of institution
999C5   $0 with on the fly discovered Record IDs (not for books)
773     $0 with Record ID of corresponding Journal or Conference
693/710 $0 with Record ID of corresponding experiment
* Introduces new XOAIMARCE corresponding format for OAI-PMH.
> BibFormat: new enhanced MARCXML format

- bibtasklets/bst_dump_records.py
* Fixes creation of dumps dir in bst_dump_records to not
crash in case the directory already exists.
> BibTasklet: bst_dump_records existing dir

- bibcheck/rules.cfg
This rule ensures that there is a valid texkey in 035__a with provenance SPIRESTeX or INSPIRETeX and otherwise generates one. 
> BibCheck: add texkey rule

- bibcheck/plugins/fix_inspireid.py
* Introduces new fix_inspireid plugin that amends broken INSPIRE IDs
based on a configuration variable (see the source code).
> BibCheck: new fix_inspireid plugin

- webstyle/webstyle_templates_inspire.py
* Disables inline ugly presentation of URLs that Bootstrap
automatically injects when a page is printed.
> WebStyle: no URL when printing

- bibtasklets/bst_consyn_harvest.py
Elsevier started using URL containing spaces around 11/2/2015.
e.g.
2015-11-09 21:38:07 --> Downloading http://consyn-delivery-prod.s3.amazonaws.com/nonbulk/AHoltkamp/47331/47331-00001-FULL-XML-NUCL PHYS B (0550-3213) 23.06.ZIP?AWSAccessKeyId=AKIAISTWDGCH3XJI3NIQ&Expires=1447681528&Signature=Y7rillZqNYhDWju44St6BA%2bwrbE%3d to /afs/cern.ch/project/inspire/uploads/elsevier/consyn/47331-00001-FULL-XML-NUCL PHYS B (0550-3213) 23.06.ZIP
This patch converts all spaces in the url string to '%20'.
A more robust fix is to change miscutil/lib/filedownloadutils.py to use urllib.quote() on all but the domain part of the url.
> BibTaskLet: consyn harvest urlescape

- bibformat/format_elements/bfe_INSPIRE_links.py
there are at least 3 different journals in Euclid which have different prefix in report number.
therefore "euclid.cmp" cannot be part of the baseurl and instead should be part of the report number
e.g. Inspire has in 035__a (with 035__9:EUCLID)
euclid.cmp/1103942536
euclid.ojm/1200780357
euclid.atmp/1117751920
T.
> BibFormat: correct links for Euclid

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Fixes bfe_INSPIRE_enhanced_marcxml bug where claims where actually
never successfully exported.
> BibFormat: exporting claims

- bibtasklets/bst_cnumcatchup.py
Bad metadata can lead to many matches. In particular an empty field 773__w:"" will trigger a global reformat, since the search matches all records. Avoid this by ensuring that the cnum field is longer than 3 characters
> BibTaskLet: ignore empty cnum

- bibtasklets/bst_consyn_harvest.py
- bibtasklets/bst_hal.py
Bibtasks which run longer than a few minutes, in particular those that rely on remote connections should allow for "sleeping" when monotasks are about to run. Otherwise bibsched will suspend all tasks until the non-sleeping bibtasklet is completed. This unnecessarily delays many indexing processes etc. 
This patch inserts some task_sleep_now_if_required() at suitable spots
> BibTaskLet: task-sleep checks for harvests

- bibformat/format_elements/bfe_INSPIRE_abstract.py
* Implements the final solution for abstract escaping,
respecting MathML, respecting pure text, respecting entitites.
> BibFormat: abstract escaping

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
- bibtasklets/bst_dump_records.py
- bibtasklets/bst_prodsync.py
* Respects CFG_BIBFORMAT_HIDDEN_TAGS configuration within the XME
format, thus effectively hiding hidden fields to unauthorized users
exporting in the INSPIRE enhanced format.
* Amends bst_prodsync to dump record as superadmin.
* Amends bst_dump_records to dump records in XME format.
> BibFormat: hidden fields in XME

- bibformat/format_elements/bfe_INSPIRE_Hep_Erratum.py
* display issue number after year in pubnote
* avoid duplicate pubnotes from repeat metadata
This introduces issue number to the pubnote in the detailed record display. The format element is somewhat misnamed as bfe_INSPIRE_Hep_Erratum.py . In fact it displays all pubnotes.
It probably should be combined with bfe_INSPIRE_publi_info.py, which is used for brief and latex formats. I don't know why it was split off. 
Effect is visible here:
http://inspireheptest.cern.ch/search?p=773__n%3A%2F.*%2F&cc=HEP&f=&sf=earliestdate&so=d&of=hd&rg=250
Also avoiding duplicate pubnote from when MARC tag 773 is inadvertently repeated in the metadata e.g. http://inspirehep.net/record/55886 vs http://inspireheptest.cern.ch/record/55886
> BibFormat: show issue number in pubnote

- bibformat/format_templates/text_Latex_CV.bft
* Following Thorsten's suggestions, no longer escapes URL and put
inspire_date on a dedicated line.
> BibFormat: fix text_Latex_CV improvements

- bibformat/format_elements/bfe_INSPIRE_Hep_Erratum.py
Inspire has a few records which are standalone errata or addenda. In those cases the pubnote should be printed normally. This improves on 2ed6b49
> BibFormat: standalone erratum pubnote display

- bibtasklets/bst_consyn_harvest.py
* Removes the unnecessary check if file already exists when extracting
ZIP files because we actually want to get latest versions in case it
was updated.
CC @fschwenn
> bibtasklets: consyn harvest always extract

- bibformat/format_elements/bfe_report_numbers.py
- bibformat/format_templates/text_Latex_CV.bft
requested by LHCb to include report numbers in the CV format
https://app.asana.com/0/3728178550980/131426425272078
this patch unconditionally adds report numbers up to limit="9999". I also added a DOI: prefix to the doi, when present.
I seriously looked at utilizing BFE_INSPIRE_PUBLI_INFO_LATEX  to replace DOI, pubnote, arXiv, repno elements, but the amount of necessary tweaks is excessive.
> BibFormat: add repno to cv-ltx format

- bibformat/format_elements/bfe_report_numbers.py
previous commit changed behavior from returning empty string to returning None
this reverts that change
> BibFormat: default repno is empty string

- bibformat/format_elements/bfe_INSPIRE_links.py
After replacing hardcoded URLs in 8564 with persistent identifiers stored in 035 the format is adjusted to display service specific links based on those identifiers.
This patch addresses OSTI links.
> BibFormat: link OSTI id from 035__a

- bibcheck/rules.cfg
* rule to replace en-dash in page-range (773__c)
with hyphen
Note that plugin regexp_replace doesn't handle unicode strings for patterns and using unicode character classes doesn't seem possible. It would be better to handle a wider range of hyphen equivalents, e.g. en- and em-dash and others
ur'[\u2010-\u2014]'. The parsing of bibcheck rule options does not appear to allow for that.
> BibCheck: replace en-dash with hyphen

- bibcheck/plugins/delete_field_matching.py
- bibcheck/rules.cfg
* plugin to remove entire MARC tag if it matches
criteria in pattern and subfield_filter
* addition to rules to remove bogus report numbers
> BibCheck: plugin to selectively delete a field

- bibformat/format_elements/bfe_INSPIRE_title_brief.py
- bibformat/format_templates/text_Latex_CV.bft
* introduces 'mode' option to bfe_INSPIRE_title_brief
* mode='tex'
escapes '%' and '_' in titles
transcribes '->' to '$\,\to\,$'
and other sanitizations
> BibFormat: CV format fix common TeX issues

- bibcheck/rules.cfg
* normalizes author names to use ascii apostrophe instead
of unicode right single quotation mark for unambiguous
search and author profile -- even though U+2019 is
typographically preferred
> BibCheck: convert U+2019 to U+0027 in author name

- bibcheck/rules.cfg
Kirsten's unwanted rule removed
> BibCheck: remove rule for isbn in refs

- bibtasklets/bst_prodsync.py
* Reverses the order of records being synced, so that one can
quickly have latest records already in the dump.
> prodsync: sync records from latest to earliest

- bibconvert/oaiarXiv2inspire.xsl
- bibconvert/oaiarXiv2inspire_nofilter.xsl
* Improves "for the" matching used to spot collaborations, so that it
does not match:
"The Abdus Salam International Centre for Theoretical Physics".
> bibconvert: improve "for the" matching

- bibedit/record_article.xml
- bibedit/record_book.xml
- bibedit/record_book_chapter.xml
- bibedit/record_conference_paper.xml
- bibedit/record_data_template.xml
- bibedit/record_preprint.xml
- bibedit/record_proceedings.xml
- bibedit/record_thesis.xml
- bibedit/volatile_check_HEP.xml_ignore
- bibedit/volatile_check_data.xml_ignore
* Adds volatile fields for ORCIDs in templates.
> bibedit: add ORCID to templates

- bibcheck/plugins/ostimove.py
plugin to remove URLs with OSTI identifiers in 8564 and replace with the information stored in 035 instead
> BibCheck: move OSTI url to 035

- bibformat/format_elements/bfe_INSPIRE_links.py
OSTI links were replaced with corresponding identifiers in 035
There should be no more OSTI links in 8564 (once Heath finishes the cleanup of the remaining leftovers). This ensures that leftover links are skipped and no inadvertent double linking from 035 and 8564 happens.
> BibFormat: no more OSTI links in 8564

- bibrank/citation.cfg
This introduces a secondary or alternate pubinfo with the same structure as the regular pubinfo. It is intended for variations or alternate forms that should not be displayed or exposed to the user, however they are used by bibrank for citation matching. An accompanying PR will be issued for the invenio repo.
> BibRank: adds alternate pubinfo field

- bibformat/format_elements/bfe_INSPIRE_exp_acronym.py
- bibformat/format_templates/Exp_HTML_brief.bft
- bibformat/format_templates/Exp_HTML_detailed.bft
* properly escapes search string
* introduces new format element for exp acronym
* removes unwanted ln=en parameter
* fixes HTML errors
This is in response to a user complaint about the incorrect links for the SNO+ experiment, i.e. 
https://inspirehep.net/record/1108233
where the searches are not properly urlescaping the '+'
> BibFormat: urlescape links in Experiments HD format

- bibtasklets/bst_fermilab_research_glance.py
Fermilab should use https for its requests
(internal policy)
> BibTaskLets: use https urls for fermi

- bibformat/format_elements/bfe_INSPIRE_Hepnames_Arxiv.py
arXiv author authority URLs are strictly ascii. This patch fixes the links to arXiv authority records for HepNames records with non-ascii names. It also avoids incorrect splitting of first initials which are non-ascii.
> BibFormat: asciify arXiv author authority links

- bibcheck/notimechange-rules.cfg
runs plugin `remove_empty_fields` on HEP and HepNames with `--notimechange`
> BibCheck: rule to remove empty fields

- bibcheck/plugins/kekmove.py
This moves KEK ids in hardcoded URLs (which are dead now) to 035 in order to make them accessible again.
I adapted the OSTI case in https://github.com/inspirehep/inspire/blob/master/bibcheck/plugins/ostimove.py as suggested by @tsgit
> BibCheck: move KEK url to 035

- bibcheck/rules.cfg
check Conference records for lat/lon coordinates and use google geocode plugin to add them if missing
an initial chunked run was done in order to not exceed google api limits for free access
> BibCheck: geocode Conferences

- feedboxes/portalbox-017-Experiments-rt-100.html
new gandi email alias was set up today 12/5/2016 for `experiments@inspirehep.net`
RT procmail config was adjusted to route email addressed to `experiments@inspirehep` to `EXP` queue
This patch updates the info on the Experiments portalbox
> PortalBox: update experiments email

- bibcheck/plugins/rename_subfield_filter.py
* correcting docstring examples
* rules.cfg is parsed as json
- use double quotes for string
- true/false instead of True/False
- no tuples, lists instead
- r' ' for pattern does not work
* casting subfield_filter to tuple
> BibCheck: bugfixes in plugin

- bibcheck/plugins/add_alice_inspireid.py
adding two missing close parenthesis ')'
> BibCheck: fix syntax error in plugin

- bibcheck/rules.cfg
check  and replace recids in 999C50 if the target record was deleted and superseed with new recid
> BibCheck: superseeded recid replacement rule

- bibcheck/plugins/refcheck.py
`search_unit(f='doi', p=val)` fails because `get_index_id_from_field('doi')` returns `0`
`search_unit(f='doi', p=val, m='a')` works because it uses `get_field_tags(f)` in addition 
I think that's a problem in search.
> BibCheck: fix doi lookup

- bibformat/format_templates/text_Latex_CV.bft
* Improves usability of CVLaTeX output format by prefixing citation
line with: "%Citations: " to make it easy to our user to search and
enable the line.
> BibFormat: cvlatex usability

- bibharvest/bibfilter_oaipos2inspire.py
_PoS_ switched to mandatory use of `https`.
> BibFilter: update base_url for POS

- bibharvest/bibfilter_oaipos2inspire.py
*PoS* appears to have switched to _relative_ URLs for fulltext (PDF) source, e.g. https://pos.sissa.it/contribution?id=PoS(unesp2002)001
has in the HTML source:
```
<p>Contribution: <a href="/archive/conferences/008/001/unesp2002_001.pdf">pdf</a></p>
```
so in order to download those PDF files `https://pos.sissa.it` needs to be prepended. 
For example look at bibsched log 
/opt/cds-invenio/var/log/bibsched/44/bibsched_task_444800.log
```
Traceback (most recent call last):
File "/opt/cds-invenio/bin/bibfilter_oaipos2inspire.py", line 207, in <module>
main(sys.argv[1:])
File "/opt/cds-invenio/bin/bibfilter_oaipos2inspire.py", line 122, in main
download_url(url, "pdf", filename, 5, 60.0)
File "/usr/lib64/python2.6/site-packages/invenio/filedownloadutils.py", line 110, in download_url …
```
> BibFilter: handle relative PDF URLs

- bibformat/format_elements/bfe_references.py
This is a fix for the detailed reference format to properly resolve and display cited records via DOIs with a `doi:` prefix in `999C5a`
I think something similar is needed for `hdl:` handles !?
> BibFormat: handle doi: prefix in ref lookup

- bibcheck/plugins/ref_jvolume.py
- bibcheck/rules.cfg
* moves letter before volume number in references for given journal in volume-range
* similar fix for PLA as soon as 773 is cleaned
* the first time this HAS TO RUN WITH NOTIMECHANGE
> bibcheck: new plugin - ref_jvolume

- bibformat/format_elements/bfe_references.py
as discussed on standup we should no longer link things in references display which are missing prefix `doi:` or `hdl:`
in `999C5a` so that cataloguers can see that something is missing.
> BibFormat: require doi/hdl prefix in refs

- bibharvest/bibfilter_oaipos2inspire.py
- bibtasklets/bst_scoap3_importer.py
@kaplun 
this is a followup to HAL timeout already merged
https://github.com/inspirehep/inspire/pull/284
I looked for other uses of requests.get() without specified timeout and added these two. Also https://github.com/inspirehep/inspire/pull/284 could maybe be improved with a try/except ?
> BibTaskLets: ensure request timeout

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Fixes exporting 961 fields in XME, where $c and $x were swapped
WRT the official documentation.
(closes #287)
> bibformat: XME correct 961

- bibcheck/plugins/isbn_normalize.py
remove hyphens and other separators from ISBNs in `020__a` and `999C5i`. Also remove leading or trailing clutter.
> BibCheck: isbn normalization plugin

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Due to a known bug in perform_request_search query parsing, if an institution
contains a single quote in the name, the previous implementation of
get_institution_ids() was broken. This implements a work-around.
> bibformat: fix XME institution matching

- bibtasklets/bst_align_hepnames_and_bais.py
> bst_align_hepnames_and_bais: ignore case conflicts

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
avoid errors from uninitialized variable.
here's an error from an Institution record which has no MARC `100` or `700`. it only has a spokesperson MARC `702`
```
* 2017-06-06 01:53:40 -> UnboundLocalError: local variable 'signatures' referenced before assignment (bfe_INSPIRE_enhanced_marcxml.py:201:format_element)
** User details
No client information available
** Traceback details
Traceback (most recent call last):
File "/usr/lib64/python2.6/site-packages/invenio/bibformat_engine.py", line 718, in eval_format_element
output_text = function(**params)
File "/usr/lib64/python2.6/site-packages/invenio/bibformat_elements/bfe_INSPIRE_enhanced_marcxml.py", line 201, in format_element
personid, flag = signatures.get(author_name, (None, None))
UnboundLocalError: local variable 'signatures' …
```
> BibFormat: fix xme uninitialized var

- bibtasklets/bst_hepdata.py
* Correctly computes the position of a table within a dataset.
* Reverts previous fixes that were ignoring the position as a
criteria for spotting if a record had been changed.
> bst_hepdata: final fix for position

- bibtasklets/bst_apsharvest.py
fix for when there is no `link` header, i.e. no pagination
> BibTaskLet: apsharvest handle missing link

- feedboxes/portalbox-002-HEP-rt-100.html
- feedboxes/portalbox-004-Jobs-rt-100.html
- feedboxes/portalbox-017-Experiments-rt-100.html
- feedboxes/portalbox-019-Journals-rt-100.html
Updating the HepData link in portalboxes. The old site is redirecting to https://hepdata.net/
> PortalBoxes: hepdata link update

- bibformat/format_elements/bfe_INSPIRE_title_brief.py
bibformat operates on bytestream with defaultencoding `utf-8`. proper unicode handling for word capitalization requires unicode strings.
Ideally all internal manipulations would be done on unicode strings, this piecemeal fix doesn't address the underlying issue which is pervasive in invenio.
> BibFormat: unicode aware title capitalization

- bibtasklets/bst_orcidsync.py
* Introduces new bst_orcidsync bibtasklet to sync all ORCID tokens
information to Labs via Redis
> bibtasklet: new bst_orcidsync

- bibcheck/rules.cfg
normalize DOIs in `999C5a` to include `doi:` prefix
> BibCheck: rule add doi prefix

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* When enhancing 999C5 fields, adds $z1 when $0 is already set and
isn't guessed on the spot during XME export.
> xme: add 999C5z

- bibformat/format_elements/bfe_INSPIRE_Hepnames_Arxiv.py
arXiv author search normalizes names in quirky ways. This patch 
* drops `'`
* replaces `-` with `_`
* takes only the final part of multi-part last names
> BibFormat: arXiv link syntax quirks

- bibharvest/bibfilter_oaicds2inspire.py
* When harvesting from CDS, matches incoming record not only on
035__9:CDS but also 595__a:CDS-*.
(closes #342)
> cds: match also based on 595__a:CDS-*

- bibtasklets/bst_claimsync.py
- bibtasklets/bst_orcidsync.py
* When pushing information (such as ORCID tokens and claims) via
Redis, serializes it via JSON.
> bibtasklet: serialize in JSON

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
* Workaround bug on legacy and do export correct doctype in
XME format. (Closes #310)
> XME: export correct doctype

- bibformat/format_elements/bfe_INSPIRE_doi.py
some DOIs have a `#` which needs to be urlescaped for the link to `dx.doi.org`
this affects only 14 records as of 2017-12-01
```
466698 10.1002/(SICI)1521-3978(199901)47:1/3<125::AID-PROP125>3.0.CO;2-#
554481 10.1002/1521-3978(200108)49:8/9<869::AID-PROP869>3.0.CO;2-#
599654 10.1002/1521-3978(200209)50:8/9<878::AID-PROP878>3.0.CO;2-#
496866 10.1002/(SICI)1521-3978(200005)48:5/7<637::AID-PROP637>3.3.CO;2-#
568701 10.1002/1521-3978(200209)50:8/9<896::AID-PROP896>3.0.CO;2-#
582254 10.1002/1521-3978(200209)50:8/9<959::AID-PROP959>3.0.CO;2-#
483665 10.1002/(SICI)1521-3978(20001)48:1/3<155::AID-PROP155>3.0.CO;2-#
483503 10.1002/(SICI)1521-3978(20001)48:1/3<191::AID-PROP191>3.0.CO;2-#
500750 10.1002/1521-3889(200009)9:8<589::AID-ANDP589>3.0.CO;2-#
482515 …
```
> BibFormat: urlescape # in DOIs

- bibtasklets/bst_labssync.py
* Adds new bibtasklet bst_labssync that polls Labs's redis's
key `records_to_sync_into_legacy` for records that need to be
fetched again from Labs and re-uploaded into Legacy.
> bibtasklets: new bst_labssync

- bibcheck/plugins/fix_inspireid.py
* correct the substitution of `Inspire-id` for one author 
> BibCheck: correct substitution of ids

- websubmit/Bibtex.py
fix for unsafe user input to `re`, in particular it also addresses a problem with texkeys containing unmatched `)` etc.
e.g.
```
In [13]: Bibtex.process_references(['IPTA):2013lea'], 'hx')
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-13-f6a569bace66> in <module>()
----> 1 Bibtex.process_references(['IPTA):2013lea'], 'hx')
/usr/lib64/python2.6/site-packages/invenio/websubmit_functions/Bibtex.py in process_references(references, output_format)
137                                                  output_format, 'en')
138                     # update bibitem and cite if they don't match
--> 139                     if not re.search('bibitem{' + ref + '}', formated_rec):
140 …
```
> WebSubmit: bibtex tool fix

- bibformat/format_templates/Default_HTML_detailed.bft
remove errant space after affiliation enclosed in parens
> BibFormat: remove space after aff in HEP detailed

- bibformat/format_elements/bfe_INSPIRE_authors.py
- bibformat/format_templates/Default_HTML_detailed.bft
ensure there is a separator at the continuation point between authors before and after expansion of long author lists 
> BibFormat: add missing separator in authors

- bibharvest/bibfilter_oaiarXiv2inspire.py
Quick hack to disable `inserts` of new arXiv records from OAI harvest on legacy. Updates continue to be processed.
> BibHarvest: disable OAI arXiv inserts

- bibcheck/plugins/fermilab_coll.py
- bibcheck/rules.cfg
-Add fermilab_coll bibcheck plugin to add 980__a:Fermilab to HEP records with a Fermilab report number
-Add rule to rules.cfg to run fermilab_coll on HEP records filtered by records w/ Fermilab report numbers that aren't already in the Fermilab collection
> Bibcheck: add fermilab_coll plugin and update rules.cfg file

- bibformat/format_elements/bfe_INSPIRE_enhanced_marcxml.py
INSPIRE IDs are sometimes derived based on other information in the HEP
record, so can contain mistakes and we don't want to consider them as
ground truth for author disambiguation.
This partly reverts e23123d90d5b5c7eaa3bbeac40330474092725e6.
> bibformat: ignore INSPIRE IDs for claims in XME

- bibformat/format_elements/bfe_INSPIRE_pdg.py
properly html-escape `('<', '&', '>')` in the PDG link text. out of 10k PDG codes about 224 contain a `<` which can lead to bungled display
> BibFormat: html-escape PDG values

- bibtasklets/bst_prodsync.py
recids of HepNames associated to a signature get exposed in the XME
format, so a new association of a HepNames to an author profile should
flag all HEP records in that profile for prodsync.
> BibTasklets: send record to prodsync on BAI change

- bibtasklets/bst_scoap3_importer.py
this avoids attaching another revision with the same checksum as any previous revisions, and in particular it addresses flip-flop from having a fulltext and an addendum being alternatingly attached
e.g.
```
$ bibdocfile --get-info -d 2301294 | grep checksum
1396328:2301294:1:.pdf:checksum=2843dbcdb7e64f49098eed600dd219da
1396328:2301294:2:.pdf:checksum=861ad6dc3ae62b6b0dda9f8a0814b602
1396328:2301294:3:.pdf:checksum=2843dbcdb7e64f49098eed600dd219da
1396328:2301294:4:.pdf:checksum=42e57cf8ca19b7eee2c98c6baf408d49
1396328:2301294:5:.pdf:checksum=2843dbcdb7e64f49098eed600dd219da
1396328:2301294:6:.pdf:checksum=42e57cf8ca19b7eee2c98c6baf408d49
1396328:2301294:7:.pdf:checksum=2843dbcdb7e64f49098eed600dd219da
1396328:2301294:8:.pdf:checksum=42e57cf8ca19b7eee2c98c6baf408d49 …
```
> BibTaskLet: avoids redundant scoap3 downloads

- bibtasklets/bst_prodsync.py
* use controlfield `005` in addition to bibrec table
to capture all modified records
e.g.
```
In [26]: last_run = '2018-08-13 18:26:53'
In [27]: modified_records = intbitset(run_sql("SELECT id FROM bibrec WHERE modification_date>=%s", (last_run, )))
In [28]: len(modified_records)
6
In [29]: compacttime = last_run.replace('-', '').replace(' ', '').replace(':', '')
In [30]: notimechangerecs = search_unit("%s->20250101000000" % compacttime, f='005', m='a')
In [31]: len(notimechangerecs)
7
In [32]: modified_records
intbitset([1639031, 1686707, 1686708, 1686709, 1686710, 1686711])
In [33]: notimechangerecs
intbitset([482380, 1639031, 1686707, 1686708, 1686709, 1686710, 1686711])
In [34]: modified_records += notimechangerecs
In …
```
> BibTaskLet: fix modified rec search in prodsync

- bibcheck/plugins/fermilab_coll.py
- bibcheck/rules.cfg
-Added rule to look for Fermilab slide and poster records in HEP and run through fermilab_coll
-Updated fermilab_coll plugin to remove 980__a:HEP from Fermilab slide and poster records
> BibCheck: update fermilab_coll.py and rules.cfg

- bibcheck/rules.cfg
Existing rule expand_subject runs currently on HEP only.
Expand to all collections.
> BibCheck: expand_subject for all collections

- bibedit/record_fermilab.xml
- bibedit/volatile_check_fermilab.xml_ignore
* Adds a template for the internal fermilab collection
based on the HEP article template.
* Without 980__a:CORE as such records would be in HEP.
> bibedit: adds template for Fermilab collection

- bibformat/format_templates/Inst_HTML_brief.bft
- bibformat/format_templates/Inst_HTML_detailed.bft
* Do not display subfield `110__t` in Institution records 
> BibFormat: skip 110t in Inst display

- bibformat/format_elements/bfe_INSPIRE_inst_children.py
Don't use `110__t` for name of child institution. `110__u` is the appropriate field.
`110__a` is a failsafe in case of bad metadata.
> BibFormat: don't use 110__t for child inst

- bibedit/volatile_check_institution.xml_ignore
* Adds 035__9:GRID to volatile_check_institution.xml_ignore to avoid
removal of it by bibcheck.
> bibedit: add GRID to volatile_check_institution.xml_ignore

- bibformat/format_elements/bfe_INSPIRE_bibtex.py
the optional `type` field can be used to overwrite/augment the `@entry` type
use this to distinguish a Habilitation thesis from a PhD thesis
@michamos needs forward port ?!
> BibFormat: adds type habilitation to bibtex

- feedboxes/portalbox-009-HepNames-rt-100.html
-update dead directory links of DESY, IHEP, JLAB, KEK, and Rutherford
> Feedboxes: update HEPNames links

- bibtasklets/bst_prodsync.py
* the XME format contains BAI identifiers of authors, so records need to
be selected for prodsync when the BAI changes. However, other updates to
the aidPERSONIDDATA table are irrelevant, so the query can be restricted
in order to trigger less prodsync activity.
> tasklets: smarter author query in prodsync

- bibcheck/plugins/fix_inspireid.py
-Added Zhang, Huaqiao (correct INSPIRE-ID) to fix_inspireid.py
-Added Ahmad, Muhammad (change name to separate author signatures) to fix_inspireid.py
-Wang, Jian (change name to separate author signatures) to fix_inspireid.py
-2019-3-22 updated commit to add numerals to names rather than shorten to initials
> BibCheck: updated fix_inspireid plugin

- bibformat/format_elements/bfe_INSPIRE_Hepnames_ORCID.py
- feedboxes/portalbox-009-HepNames-rt-100.html
* use https for orcid links in HepNames
* update orcid link in HepNames feedbox to https
> BibFormat: use https for links to orcid

- bibformat/format_elements/bfe_report_numbers.py
A while back the `710__g` field was normalized to not contain the word collaboration any longer. This updates the Fermilab report_number exclusion
accordingly.
> BibFormat: update match string from Atlas/CMS

- bibformat/format_elements/bfe_report_numbers.py
All report numbers in `037__a` should be displayed. 
Fermilab report numbers that should be hidden must be in `037__z`
> BibFormat: remove skip rule for fnal repno

- bibformat/format_elements/bfe_INSPIRE_abstract.py
On legacy python 2.6, old lxml, old bs4 utf-8 encoded strings are not well handled by BeautifulSoup. Hence ensure they are decoded.
> BibFormat: fix bs4 handling of utf-8

- bibcheck/plugins/fix_inspireid.py
-Corrects CMS author Chen Geng's ORCID in HEP
> BibCheck: added line to fix Geng, Chen ORCID to fix_inspireid

- websubmit/Bibtex.py
- websubmit/bibtex_unit_test.py
-Updated Bibtex.py used in BiblioTools to accept ADS bibcodes as citations
-Added unit test for ADS bibcodes
> WebSubmit: update to Bibtex.py

- bibtasklets/bst_apsharvest.py
this bibtasklet uses the `bibdocfile.open_url()` method
recently bibdocfile was updated to use `requests` instead of `urllib2.urlopen`
https://github.com/inspirehep/invenio/commit/9d8118136d73dd37863c7e1b50ff44fea8a78cf7
this patch fixes some differences in behaviour caused by that change
> BibTaskLet: adapts bst_apsharvest to use of requests

- webstyle/webstyle_templates_inspire.py
* add a meta tag `viewport` to html head section for google crawler's 
determination of mobile friendliness
* the viewport could be set more generally, but while some pages improve
others require some adjustments for true mobile friendliness 
> WebStyle: adds meta viewport for Googlebot

- bibformat/format_elements/bfe_INSPIRE_bibtex.py
* avoid output of "page (year)" only or otherwise incomplete pubnote,
e.g. a reprint pointer in 773 which has only $0 and $c, or similar
> BibFormat: avoid output of only page info

- bibformat/format_elements/bfe_texkey.py
* handles multiple MARC tags 035 for texkeys
instead of taking info from the last one
> BibFormat: select proper texkey

- websubmit/Bibtex.py
* substitute the original citation key in place of the Inspire texkey
for all @entry types, not just @article
> WebSubmit: fix substitute texkeys

- bibexport/sitemap.cfg
- webstyle/webstyle_templates_inspire.py
show tooltip for labs conferences in navbar
take Conferences out of legacy site-map
> WebStyle: redirect Conferences to labs

- bibcheck/rules.cfg
- Remove trailing comma from 100 and 700 fields in HEP
> BibCheck: Clean one name authors

- bibexport/sitemap.cfg
- webstyle/robots.txt
* prepare for switch to new platform
* remove HEP and HEPNames from sitemap
* update robots.txt to use old.inspirehehp.net URL
> BibExport: remove HEP from sitemap

- bibtasklets/bst_arxiv_doi_update.py
normalize journal names with same knowledgebase refextract is using
```
In [1]: from invenio.refextract_kbs import get_kbs
In [2]: from invenio.docextract_convert_journals import mangle_value
In [3]: jkb = get_kbs()['journals']
In [4]: mangle_value(jkb, 'Phys.Rev.Research')
'Phys.Rev.Res.'
```
> BibTaskLet: normalize journal names

- bibtasklets/bst_check4template.py
* 87fd734 removed the templates for Jobs and Conferences.
No new records of this type should be created on legacy any longer.
Existing records should not be edited on legacy any longer.
> BibTaskLets: remove jobs/conf template check

- bibtasklets/bst_consyn_harvest.py
* Adds 'dis' to INTERESTING_DOCTYPES such that also dis-cussions,
i.e. paper of the type "Comment to ..." are included.
> bst_consyn_harvest.py: add 'dis' as interesting doctype

- bibexport/sitemap.cfg
Institutions and Experiments are now available on labs and should be crawled there
> BibExport: trim inst/exp from sitemap
